# Cloudflare Pages Build Configuration

# Build settings
[build]
  command = "npm install && npm run build"
  publish = ".next"

# Environment settings  
[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_CONFIG_PRODUCTION = "false"
  NEXT_TELEMETRY_DISABLED = "1"

# Functions settings for Next.js API routes
[functions]
  node_compat = true
